name       : python-pivy
version    : 0.6.8
release    : 4
source     :
    - https://github.com/coin3d/pivy/archive/refs/tags/0.6.8.tar.gz : c443dd7dd724b0bfa06427478b9d24d31e0c3b5138ac5741a2917a443b28f346
license    : ISC
component  : programming.python
summary    : Python bindings to coin3d
description: |
    Pivy is a Coin binding for Python. Coin is a high-level 3D graphics library with a C++ Application Programming Interface. Coin uses scene-graph data structures to render real-time graphics suitable for mostly all kinds of scientific and engineering visualization applications.
builddeps  :
    - pkgconfig(SoQt)
    - pkgconfig(glu)
    - pkgconfig(python3)
    - swig
setup      : |
    %patch -p1 < $pkgfiles/coin3d-include-path.patch
build      : |
    %python3_setup
install    : |
    %python3_install
